name: CI/CD — SESS Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pipeline success
        run: echo "✅ Pipeline SESS exécuté avec succès!"
